repos:
  - repo: https://github.com/psf/black
    rev: 21.10b0
    hooks:
      - id: black
        language_version: python3.12
  # - repo: https://github.com/pytest-dev/pytest
  #   rev: v7.2.1
  #   hooks:
  #     - id: pytest
